version: 0.0.0

server:
  port: 9090 
spring:
  application:
    name: tokio
  datasource:
    url: jdbc:mysql://192.168.15.7:3306/estudo_db?allowPublicKeyRetrieval=true&useSSL=false
    username: rodrigo
    password: rodrigo
  jpa:
    database: default
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format-sql: true
        generate-statistics: true
  main:
    banner-mode: "LOG"
    allow-bean-definition-overriding: true